//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Nick = "\"\"";
            this.Hash = "\"\"";
            this.Salt = "\"\"";
            this.Email = "\"\"";
            this.State = 0;
            this.Games = new HashSet<Game>();
        }
    
        public long PlayerID { get; set; }
        public string Nick { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public string Email { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
